const bodyParts = [
  {
    id: 1,
    title: "Arm",
    bigtext:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  },
  {
    id: 2,
    title: "Leg",
    bigtext:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris metus nulla, feugiat sit amet mauris in, pellentesque egestas purus. Aliquam mollis est id metus vestibulum, ut porttitor leo tempus. Phasellus eget mi accumsan, convallis eros consectetur, congue massa. Phasellus sed facilisis sem. Aliquam ligula leo, ullamcorper in purus sed, faucibus suscipit mauris. Aenean at metus et sem semper sodales. Praesent pellentesque tellus a urna varius faucibus. Aliquam non luctus ex. Praesent et lacinia nibh, vitae sollicitudin turpis. Donec semper lectus ac velit convallis fringilla.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris metus nulla, feugiat sit amet mauris in, pellentesque egestas purus. Aliquam mollis est id metus vestibulum, ut porttitor leo tempus. Phasellus eget mi accumsan, convallis eros consectetur, congue massa. Phasellus sed facilisis sem. Aliquam ligula leo, ullamcorper in purus sed, faucibus suscipit mauris. Aenean at metus et sem semper sodales. Praesent pellentesque tellus a urna varius faucibus. Aliquam non luctus ex. Praesent et lacinia nibh, vitae sollicitudin turpis. Donec semper lectus ac velit convallis fringilla.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris metus nulla, feugiat sit amet mauris in, pellentesque egestas purus. Aliquam mollis est id metus vestibulum, ut porttitor leo tempus. Phasellus eget mi accumsan, convallis eros consectetur, congue massa. Phasellus sed facilisis sem. Aliquam ligula leo, ullamcorper in purus sed, faucibus suscipit mauris. Aenean at metus et sem semper sodales. Praesent pellentesque tellus a urna varius faucibus. Aliquam non luctus ex. Praesent et lacinia nibh, vitae sollicitudin turpis. Donec semper lectus ac velit convallis fringilla.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris metus nulla, feugiat sit amet mauris in, pellentesque egestas purus. Aliquam mollis est id metus vestibulum, ut porttitor leo tempus. Phasellus eget mi accumsan, convallis eros consectetur, congue massa. Phasellus sed facilisis sem. Aliquam ligula leo, ullamcorper in purus sed, faucibus suscipit mauris. Aenean at metus et sem semper sodales. Praesent pellentesque tellus a urna varius faucibus. Aliquam non luctus ex. Praesent et lacinia nibh, vitae sollicitudin turpis. Donec semper lectus ac velit convallis fringilla.",
  },
];

export default bodyParts;
